version: 2
jobs:
  build:
    parallelism: 1
    docker: # run the steps with Docker
      - image: circleci/ruby:2.7.3-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      # Check out source code to working directory.
      - checkout

      - run:
          name: Update bundler
          command: gem install bundler

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          key: jahuty-bundle-{{ checksum "Gemfile.lock" }}

      # Install Ruby dependencies.
      - run:
          name: Bundle Install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle

      # Store bundle cache for Ruby dependencies.
      - save_cache:
          key: jahuty-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run rubocop
          command: bundle exec rubocop

      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # See https://circleci.com/docs/2.0/deployment-integrations/ for example deploy configs
